version: "3.8"

services:
  laravel-local:
    container_name: laravel-local
    build:
      context: ./
      dockerfile: Dockerfile.local
    platform: linux/amd64
    ports:
      - 8000:80
    volumes:
      - ./:/app:cached
    tty: true
    depends_on:
      - db-local
    networks:
      - mochiben-network
  db-local:
    container_name: db-local
    build:
      context: ./mariadb-dockerfile
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mochiben
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: mochibendbuser
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - db-local-volume:/var/lib/mysql:cached
    networks:
      - mochiben-network

volumes:
  db-local-volume:

networks:
  mochiben-network:
    name: mochiben-network
