version: "3.8"

services:
  front-local:
    container_name: front-local
    build:
      context: ./front
      dockerfile: Dockerfile.local
    platform: linux/amd64
    volumes:
      - ./front:/app:cached
    command: "yarn dev"
    ports:
      - 80:3000
    stdin_open: true
    tty: true
    depends_on:
      - laravel-local
  laravel-local:
    container_name: laravel-local
    build:
      context: ./
      dockerfile: Dockerfile.local
    platform: linux/amd64
    ports:
      - 8000:80
    volumes:
      - ./:/app:cached
    tty: true
    depends_on:
      - db-local
  db-local:
    container_name: db-local
    build:
      context: ./mariadb-dockerfile
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mochiben
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: mochibendbuser
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - db-local-volume:/var/lib/mysql:cached

volumes:
  db-local-volume:
